travis:
  secure:
    BINSTAR_TOKEN: Wb2HumR/m9y7W6kcE+8HPAqxMu8YpJAO9SiHW0Otpv0Y4hNzTk/Cqdy+uDs6LRNjcHhD36SZysF0BgJcI3K1ZbN8eNjYA2XhNnbzwx160poqQb65+xIOlRs1EP/5t2dhmCXjD6sxBJFI6nVCg+y2kkpikoBOgu3Dyy5o6YpgO8oh/mggyxPqHj1qd+RMfkrsSM+vkqmm2VupsYzcj44shuRkS2/HVUtkhQjTUgQKepwR6sVzDs8XSKsSXDOQEriH2d6/WHW9tnTdJXnCRRI+Swe14jUb8vLeMpGaDW7gzbOM/nfbuu4kL2c8fmrO9r32eh7jjqgkgfxTPWGIdTN5H6q68mMRCCQY3GEbmVas8r+aRtyeZ8Owj6/PxQTquXQCEMzEMM39w8CEFF3dGZ3qbnnOZRSdl5hwuoMZr8xiVXPgjUfweuCsEkcn0ynQc3exoWp7Zx7TcahjX5mY7k3F4l6UGht5OMLMQhONEFzY4AeLEsAn0nLiwbuubFhkDns2ouhUuc7wucgRWRVsVAbKEw92zm0FRuOpdemIgk3DhLYI4/J+jrr6djey6H60Zrz0szX6ykUdPO/BO024kkbdySjvupJUqPWvRlvG0cjDLBJ0T15KXkRy6UEIpQFhI+40y3YKrt4+OpyYFe+SKozB+JAuxHgaAY7kGD+bUI2+yTU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
