travis:
  secure:
    BINSTAR_TOKEN: kh7tzkbgLvmL7BASOfi/b1hAIC/8ajrXikFSkhUMbmc7tGKZaiFeb4KJ/uA0oA8MXjR+rAk7m58BmovH9TUeoTenwPrB0N9DfRfdFDipgbbIZ2Zxy0OaNL07XDBn0xT6Qmf6TomFRr1JOXl+j9VjW34GEP9lR8SbrZsKVDIKYHqnK54fLcoKxZqh027XwAuaCOzUVBPsMCn2zVq1KegQetxsJ6gArc7pSIZ4/ujFDOBXjdoebvQSArrl1niNjHESqhjmSkpSvFeIhTkdT6yFg3rZaWu9K4Ues00+gehjBEWOf28InOlca0UmHSE8oChfxleBHO1Yz7rV3UM5l099XUukm+mvHhivnoaG38dn6AzA1LZwio940SAhRoLSsk3iSZgbfHaUEpFLU5w4jBgmFSmzxZK+M9BjmDw3huUZPW6wsjhy3DpZrO8L15DwSztsIXK0qJnRV5bZwQWvLZHUkhelUQrMLk/Nad9m3HPWvRgPll3j3FRKXkBPvjrSD0lRXZ4+lY0BZ7Y4MQ3K4Yf9EH8n9Bsrxc1cd34gcjJgEwRg/CajAx3X2P6G58LAKp9Qz7Z9/RiNPJpv/BEqFP/t7VZaamIdgxtXCpzJ82Qj1c7YkoJXPdGEbxjqmHFJdojdV1VEgVN8TvRxAPF3c+4ReBFMfENF16VPlRa8hAZN6nM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
