travis:
  secure:
    BINSTAR_TOKEN: SVf8aQp+X0pSnt2ZtaFvb6oj6do2uu7xtNhbnjOswp9GjBQLs9n7Hp2xzI8Qi1D8bG91HobIdBDz9Lixm0O/fhoueTFFbhkUXfE/Ec9qd1caeDw408/BE9GJpQNC8GPFvoP3wjVa8UA1nlpY33KDLDS2batMZF+d3YrDgXCNCHvY1r/2wzU2k/Q+eHPNU2uBvDLyS7fizPAnKt3NybR3d2eOyQ9kT5quTKoiZq48PpiGubNJXOW05td0HyekEuwFMtDuAueOJsvov64GKFG3nhaLZ9/MbJMM+QOwvGpdlors7ypjU21rDfdfrOp9qYVfvjOWI4kGL7ZYPRZz8zAPnMu44DpBgXZZaQmPNGM5h1KrGBgO+PBwP5urGZiv8/DOoip6+UtTt5N/zBMgdvNPTzoVw6ZPlZd0zkKpDqc0dGCk3QoThX35amHaQOnQHkyLOid8jp3CRlqtp0OmQqLuNOQy+JRCAyoNkoPCMCB9nH2JCUZpX3M/a9/zhndno2HnTNcKz7m9MBNjEM8uMZdq1hpoIcC+nEe/B2jXSuqCkr5w2Kgg8b0EIWS96M3FaYCuL5weehKHcAUGrUtmbV+MwygNMgI6uXpznCg16pLBgPJvXXjlsRqsbYZMlH2900RVEDOMe2Wik5D5ZvimlSqxp1AT24TG81pivPw7Ueapk8M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
